name: DjangoCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy to Droplet
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - uses: actions/checkout@v2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}} #Must be unique in Heroku
          username: ${{secrets.USERNAME}}
          script: |
              cd /home/project/newdjango
              git pull
      - name: Deployed successfully
        run: |
          echo Deployed!!
